name: Deploy Site

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Release']
    branches: [main]
    types: 
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install Theme
        run: yarn --frozen-lockfile

      - name: Build Docusaurus Theme
        run: yarn build

      - name: Install Example App
        working-directory: ./example
        run: yarn --frozen-lockfile
      
      - name: Build website
        working-directory: ./example
        run: yarn build
      
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./lib
            ./example/build
          key: build-${{ github.sha }}

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Cache Build
        uses: actions/cache@v3
        with:
          path: |
            ./lib
            ./example/build
          key: build-${{ github.sha }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com