name: Release

on: 
  workflow_dispatch:
    inputs:
      bump_type:
        description: 'Bump type'     
        required: true
        default: 'minor' 
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  validate:
    uses: ifood/.workflows/.github/workflows/npm_validate.yml@main
  release:
    uses: ifood/.workflows/.github/workflows/npm_publish.yml@main
    secrets:
      NPM_DEPLOY_TOKEN: ${{ secrets.NPM_TOKEN }}
    with:
      bump_type: ${{ github.event.inputs.bump_type }}

