name: Validate

on:
  workflow_call:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  validate_code:
    uses: ifood/.workflows/.github/workflows/npm_validate.yml@main
  validate_site:
    name: Validate theme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install Theme
        run: yarn --frozen-lockfile

      - name: Build Docusaurus Theme
        run: yarn build

      - name: Install Example App
        working-directory: ./example
        run: yarn --frozen-lockfile
      
      - name: Build website
        working-directory: ./example
        run: yarn build